name: Build

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: devkitpro/devkita64:latest

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Build
        run: make -j8

      - name: Install libnx master & Retry build
        if: ${{ failure() }}
        run: |
          pushd /tmp
          git clone https://github.com/switchbrew/libnx
          cd libnx
          make -j8
          make install
          popd
          make -j8

      - name: Upload built files
        uses: actions/upload-artifact@v3
        with:
          name: sdcard
          path: out/sd

      - name: Upload elf file
        uses: actions/upload-artifact@v3
        with:
          name: ldn_mitm.elf
          path: ldn_mitm/ldn_mitm.elf

      - name: Upload elf file
        uses: actions/upload-artifact@v3
        with:
          name: ldn_mitm.elf
          path: overlay/overlay.elf
