name: Nightly

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: devkitpro/devkita64:latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      
      - name: update Atmosphere-libs
        run: |
          pushd Atmosphere-libs
          git fetch --all
          git reset --hard origin/master
          popd
      
      - name: Build
        run: make -j8

      - name: Upload built files
        uses: actions/upload-artifact@v3
        with:
          name: sdcard
          path: out/sd

      - name: Upload elf file
        uses: actions/upload-artifact@v3
        with:
          name: ldn_mitm.elf
          path: ldn_mitm/ldn_mitm.elf

      - name: Upload elf file
        uses: actions/upload-artifact@v3
        with:
          name: ldn_mitm.elf
          path: overlay/overlay.elf
